# Generated by Django 3.2.7 on 2021-10-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleService', '0002_rename_vehicledetails_vehicledetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='car_name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='vehicledetail',
            name='car_description',
        ),
        migrations.AddField(
            model_name='vehicledetail',
            name='customer_no',
            field=models.IntegerField(null=True),
        ),
    ]
